#!/usr/bin/env bash

# Update package lists and install Nginx
apt-get -y update
apt-get install -y nginx

# Set up the custom index page
echo "Holberton School!" > /var/www/html/index.html

# Update the Nginx configuration file to add the redirect
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index.html index.htm;

    server_name _;

    # Redirect /redirect_me to a new URL with a 301 Moved Permanently status
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
    }
}
EOL

# Restart Nginx to apply changes
sudo service nginx restart

